// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofyhxjtrqtnbxhekzgbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9meWh4anRycXRuYnhoZWt6Z2JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NTI5MjcsImV4cCI6MjA2MjMyODkyN30.GlJZ3qJeEATfmYsq5cestBDFplRV0rzsslnOn5zV5Gw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);